---
- name: running system_copy tasks
  ansible.builtin.include_tasks: system_copy.yml
  loop: "{{ system_copy | dict2items }}"
  loop_control:
    label: "{{ system_copy_item['key'] }}"
    loop_var: system_copy_item
  when:
    system_copy is defined
