---
- name: "{{ system_copy_item['key'] }} : copying"
  ansible.builtin.copy:
    attributes: "{{ system_copy_item['value']['attributes'] | default(omit) }}"
    backup: "{{ system_copy_item['value']['backup'] | default(omit) }}"
    checksum: "{{ system_copy_item['value']['checksum'] | default(omit) }}"
    content: "{{ system_copy_item['value']['content'] | default(omit) }}"
    decrypt: "{{ system_copy_item['value']['decrypt'] | default(omit) }}"
    dest: "{{ system_copy_item['value']['dest'] }}"
    directory_mode: "{{ system_copy_item['value']['directory_mode'] | default(omit) }}"
    follow: "{{ system_copy_item['value']['follow'] | default(omit) }}"
    force: "{{ system_copy_item['value']['force'] | default(omit) }}"
    group: "{{ system_copy_item['value']['group'] | default(omit) }}"
    local_follow: "{{ system_copy_item['value']['local_follow'] | default(omit) }}"
    mode: "{{ system_copy_item['value']['mode'] | default(omit) }}"
    owner: "{{ system_copy_item['value']['owner'] | default(omit) }}"
    remote_src: "{{ system_copy_item['value']['remote_src'] | default(omit) }}"
    selevel: "{{ system_copy_item['value']['selevel'] | default(omit) }}"
    serole: "{{ system_copy_item['value']['serole'] | default(omit) }}"
    setype: "{{ system_copy_item['value']['setype'] | default(omit) }}"
    seuser: "{{ system_copy_item['value']['seuser'] | default(omit) }}"
    src: "{{ system_copy_item['value']['src'] | default(omit) }}"
    unsafe_writes: "{{ system_copy_item['value']['unsafe_writes'] | default(omit) }}"
    validate: "{{ system_copy_item['value']['validate'] | default(omit) }}"
  when:
    - system_copy_item['value']['dest'] is defined
