---
- name: "{{ system_copy_item['key'] }} : copying"
  ansible.builtin.copy:
    attributes: "{{ system_copy_item['attributes'] | default(omit) }}"
    backup: "{{ system_copy_item['backup'] | default(omit) }}"
    checksum: "{{ system_copy_item['checksum'] | default(omit) }}"
    content: "{{ system_copy_item['content'] | default(omit) }}"
    decrypt: "{{ system_copy_item['decrypt'] | default(omit) }}"
    dest: "{{ system_copy_item['dest'] }}"
    directory_mode: "{{ system_copy_item['directory_mode'] | default(omit) }}"
    follow: "{{ system_copy_item['follow'] | default(omit) }}"
    force: "{{ system_copy_item['force'] | default(omit) }}"
    group: "{{ system_copy_item['group'] | default(omit) }}"
    local_follow: "{{ system_copy_item['local_follow'] | default(omit) }}"
    mode: "{{ system_copy_item['mode'] | default(omit) }}"
    owner: "{{ system_copy_item['owner'] | default(omit) }}"
    remote_src: "{{ system_copy_item['remote_src'] | default(omit) }}"
    selevel: "{{ system_copy_item['selevel'] | default(omit) }}"
    serole: "{{ system_copy_item['serole'] | default(omit) }}"
    setype: "{{ system_copy_item['setype'] | default(omit) }}"
    seuser: "{{ system_copy_item['seuser'] | default(omit) }}"
    src: "{{ system_copy_item['src'] | default(omit) }}"
    unsafe_writes: "{{ system_copy_item['unsafe_writes'] | default(omit) }}"
    validate: "{{ system_copy_item['validate'] | default(omit) }}"
  when:
    - system_copy_item['value']['dest'] is defined
